apiVersion: apps/v1
kind: Deployment
metadata:
  name: starswap-info-deployment
  namespace: starcoin-main
  labels:
    app: starswap-info
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starswap-info
  template:
    metadata:
      labels:
        app: starswap-info
    spec:
      containers:
        - name: starswap-info
          image: fountainchen/starswap_info_backend:sha-30c9da0
          ports:
            - containerPort: 8300
          env:
            - name: HOSTS
              value: "main.seed.starcoin.org"
            - name: NETWORK
              value: "main"
            - name: BG_TASK_JOBS
              value: "swap_transaction,swap_stats,price_hour,price_stat,swap_pool_fee_stat"
            - name: SWAP_API_URL
              value: "https://swap-api.starswap.xyz"
            - name: SWAP_CONTRACT_ADDR
              value: "0x8c109349c6bd91411d6bc962e080c4a3"
            - name: DS_URL
              value: "jdbc:postgresql://database-swap.czftx6muneg7.ap-northeast-1.rds.amazonaws.com/starcoin"
            - name: DB_USER_NAME
              value: "starcoin"
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-starcoin-yu
                  key: password
            - name: DB_SCHEMA
              value: "main"
            - name: MOVE_SCAN_API_URL
              value: "https://api.movescan.org"
